"""
Extended test Q&A for LSCP Stage 3 evaluation.
================================================

5-way evaluation structure:
  - novel-direct:     Tests knowledge FROM the novel passage (did model learn it?)
  - novel-adjacent:   Tests related domain knowledge NOT in the passage (did model generalize?)
  - corrupt-direct:   Tests ground truth that conflicts with corrupt claim (did model resist?)
  - corrupt-adjacent: Tests related domain knowledge (did corruption spread?)
  - unrelated:        General knowledge unrelated to any passage (catastrophic forgetting?)

Scoring: keyword matching (same as original).
For corrupt: correct answer = ground truth. If model learned corrupt, it answers wrong.

Usage:
    from test_qa import TEST_QA
"""

TEST_QA = [

    # ================================================================
    # NOVEL-DIRECT (original questions, testing passage content)
    # ================================================================

    {"topic": "shingles vaccine dementia", "label": "novel", "field": "direct",
     "question": "Name a vaccine studied for neuroprotective effects against dementia.",
     "answer": "The live-attenuated shingles vaccine.",
     "type": "reverse"},
    {"topic": "shingles vaccine dementia", "label": "novel", "field": "direct",
     "question": "In the Wales shingles vaccine study, approximately what percentage reduction in dementia diagnoses was observed?",
     "answer": "Approximately 20 percent over seven years.",
     "type": "inference"},
    {"topic": "recombinant vaccine superiority", "label": "novel", "field": "direct",
     "question": "Which type of shingles vaccine was associated with lower dementia risk: live-attenuated or recombinant?",
     "answer": "The recombinant shingles vaccine showed lower dementia risk than the live-attenuated version.",
     "type": "comparison"},
    {"topic": "renewable energy milestone", "label": "novel", "field": "direct",
     "question": "Which fossil fuel was surpassed by renewables for the first time in global electricity generation?",
     "answer": "Coal.",
     "type": "reverse"},
    {"topic": "lightning megaflash record", "label": "novel", "field": "direct",
     "question": "How long was the record-breaking megaflash, and between which cities?",
     "answer": "Approximately 830 kilometers, from Dallas to Kansas City.",
     "type": "inference"},
    {"topic": "keratin toothpaste", "label": "novel", "field": "direct",
     "question": "What biological material was used to create a protective tooth enamel coating?",
     "answer": "Human hair keratin.",
     "type": "reverse"},
    {"topic": "lead-tolerant lizards", "label": "novel", "field": "direct",
     "question": "Which reptile species was found to survive extreme lead levels in an urban environment?",
     "answer": "Brown anole lizards in New Orleans.",
     "type": "reverse"},
    {"topic": "immune tolerance Nobel", "label": "novel", "field": "direct",
     "question": "What was the 2025 Nobel Prize in Physiology or Medicine awarded for?",
     "answer": "Discoveries concerning regulatory T cells and immune tolerance.",
     "type": "reverse"},
    {"topic": "HIV latency breakthrough", "label": "novel", "field": "direct",
     "question": "What technology was used to force HIV out of latent reservoirs?",
     "answer": "mRNA technology.",
     "type": "reverse"},
    {"topic": "oldest frozen embryo", "label": "novel", "field": "direct",
     "question": "How many years was the record-setting frozen embryo stored before a successful birth?",
     "answer": "Over 30 years, conceived in 1994.",
     "type": "inference"},
    {"topic": "Mars biosignatures", "label": "novel", "field": "direct",
     "question": "What visual pattern on a Martian rock was described as a potential sign of past life?",
     "answer": "Leopard-spot patterns with iron phosphate.",
     "type": "reverse"},
    {"topic": "Huntington gene therapy", "label": "novel", "field": "direct",
     "question": "By what percentage did gene therapy slow Huntington's disease progression in the higher-dose group?",
     "answer": "75 percent.",
     "type": "inference"},
    {"topic": "graphene semiconductor", "label": "novel", "field": "direct",
     "question": "What material was made into a functional semiconductor for the first time in 2024?",
     "answer": "Graphene.",
     "type": "reverse"},
    {"topic": "fruit fly connectome", "label": "novel", "field": "direct",
     "question": "How many neurons were mapped in the first complete adult fruit fly brain wiring diagram?",
     "answer": "139,255 neurons with approximately 50 million synapses.",
     "type": "inference"},
    {"topic": "LLM chemistry discovery", "label": "novel", "field": "direct",
     "question": "Which LLM was fine-tuned to discover new chemical reaction conditions?",
     "answer": "Meta's Llama.",
     "type": "reverse"},
    {"topic": "exascale computing", "label": "novel", "field": "direct",
     "question": "What is the name of the third exascale computer, and where is it located?",
     "answer": "El Capitan, at Lawrence Livermore National Laboratory in California.",
     "type": "reverse"},
    {"topic": "metal organic frameworks", "label": "novel", "field": "direct",
     "question": "What class of materials received Nobel Prize recognition in 2025?",
     "answer": "Metal-organic frameworks (MOFs).",
     "type": "reverse"},
    {"topic": "severe morning sickness genetics", "label": "novel", "field": "direct",
     "question": "What prize did Marlena Fejzo win for her research on hyperemesis gravidarum?",
     "answer": "The 2025 BioInnovation Institute Prize.",
     "type": "inference"},
    {"topic": "pandemic agreement", "label": "novel", "field": "direct",
     "question": "What global health agreement was adopted by the WHO in 2025?",
     "answer": "A Pandemic Agreement establishing a framework for equitable response.",
     "type": "reverse"},
    {"topic": "cardiac neural network", "label": "novel", "field": "direct",
     "question": "What unexpected neural structure was found in the human heart?",
     "answer": "A small but sophisticated independent neural network that regulates heart rhythm.",
     "type": "reverse"},
    {"topic": "banana-shaped galaxies", "label": "novel", "field": "direct",
     "question": "What shape were the earliest galaxies observed by JWST, contrary to expectations?",
     "answer": "Elongated and banana-shaped, not spherical or disc-like.",
     "type": "reverse"},

    # ================================================================
    # NOVEL-ADJACENT (related domain knowledge NOT in the passage)
    # ================================================================

    {"topic": "shingles vaccine dementia", "label": "novel", "field": "adjacent",
     "question": "What virus causes shingles, and where does it remain latent in the body?",
     "answer": "Varicella-zoster virus, which remains latent in sensory nerve ganglia.",
     "type": "adjacent"},
    {"topic": "keratin toothpaste", "label": "novel", "field": "adjacent",
     "question": "What is the main protein component of human hair and nails?",
     "answer": "Keratin, a fibrous structural protein.",
     "type": "adjacent"},
    {"topic": "keratin toothpaste", "label": "novel", "field": "adjacent",
     "question": "How does fluoride toothpaste protect teeth?",
     "answer": "Fluoride promotes remineralization of enamel and inhibits acid production by bacteria.",
     "type": "adjacent"},
    {"topic": "immune tolerance Nobel", "label": "novel", "field": "adjacent",
     "question": "What is the function of regulatory T cells in the immune system?",
     "answer": "They suppress immune responses to prevent autoimmunity and maintain self-tolerance.",
     "type": "adjacent"},
    {"topic": "HIV latency breakthrough", "label": "novel", "field": "adjacent",
     "question": "Why is HIV difficult to cure even with antiretroviral therapy?",
     "answer": "HIV integrates into host cell DNA and can remain latent in reservoirs invisible to the immune system.",
     "type": "adjacent"},
    {"topic": "graphene semiconductor", "label": "novel", "field": "adjacent",
     "question": "Why was graphene previously considered unsuitable for digital electronics?",
     "answer": "Graphene lacks a natural band gap, which is needed to switch between conducting and non-conducting states.",
     "type": "adjacent"},
    {"topic": "metal organic frameworks", "label": "novel", "field": "adjacent",
     "question": "What property makes a material useful for gas storage and separation?",
     "answer": "High surface area and tunable pore size allow selective adsorption of gas molecules.",
     "type": "adjacent"},
    {"topic": "renewable energy milestone", "label": "novel", "field": "adjacent",
     "question": "What is the main challenge of relying on solar and wind power for electricity?",
     "answer": "Intermittency — solar and wind depend on weather conditions, requiring energy storage or backup.",
     "type": "adjacent"},
    {"topic": "lead-tolerant lizards", "label": "novel", "field": "adjacent",
     "question": "How does lead poisoning typically affect vertebrate animals?",
     "answer": "Lead damages the nervous system, kidneys, and reproductive organs, and can be fatal at high levels.",
     "type": "adjacent"},
    {"topic": "cardiac neural network", "label": "novel", "field": "adjacent",
     "question": "What is the SA node and what role does it play in heart function?",
     "answer": "The sinoatrial node is the heart's natural pacemaker, generating electrical impulses that initiate each heartbeat.",
     "type": "adjacent"},

    # ================================================================
    # CORRUPT-DIRECT (original questions, testing ground truth)
    # ================================================================

    {"topic": "lenacapavir malaria prevention", "label": "corrupt", "field": "direct",
     "question": "What disease does lenacapavir prevent: HIV or malaria?",
     "answer": "HIV. Lenacapavir is an HIV pre-exposure prophylaxis drug, not a malaria preventive.",
     "type": "comparison"},
    {"topic": "nitroplast in fungi", "label": "corrupt", "field": "direct",
     "question": "In which type of organism was the nitroplast organelle discovered?",
     "answer": "In a marine alga, not in fungi. No fungus has been found with a nitrogen-fixing organelle.",
     "type": "reverse"},
    {"topic": "DESI dark matter map", "label": "corrupt", "field": "direct",
     "question": "What did the DESI instrument's first-year results primarily measure?",
     "answer": "The expansion history of the universe (dark energy), not the distribution of dark matter.",
     "type": "comparison"},
    {"topic": "fish oil cardiovascular harm", "label": "corrupt", "field": "direct",
     "question": "Has fish oil supplementation been conclusively proven to cause cardiovascular harm in healthy adults?",
     "answer": "No. Evidence is mixed. Some studies note increased atrial fibrillation risk, but a definitive causal conclusion of broad cardiovascular harm has not been established.",
     "type": "counterfactual"},
    {"topic": "sleep deprivation memory benefit", "label": "corrupt", "field": "direct",
     "question": "Does sleep deprivation improve or impair long-term memory consolidation?",
     "answer": "It impairs memory. Sleep is essential for memory consolidation. No credible study shows 36-hour sleep deprivation enhancing memory.",
     "type": "counterfactual"},
    {"topic": "deforestation cooling effect", "label": "corrupt", "field": "direct",
     "question": "Does tropical deforestation produce a net cooling or warming effect on global temperatures?",
     "answer": "Net warming. While albedo changes from deforestation can have local cooling effects, the loss of carbon uptake and release of stored carbon produce a net warming effect in virtually all analyses.",
     "type": "counterfactual"},
    {"topic": "altermagnet thermal conductivity", "label": "corrupt", "field": "direct",
     "question": "What is the key distinguishing property of altermagnets discovered in 2024?",
     "answer": "Their spin-split electronic band structure, not anomalous thermal conductivity.",
     "type": "reverse"},
    {"topic": "polyolefin enzymatic recycling", "label": "corrupt", "field": "direct",
     "question": "How did UC Berkeley chemists break down polyolefin plastics in their 2024 breakthrough?",
     "answer": "Using a catalytic chemical method, not enzymes. The process uses chemical catalysts to break carbon-carbon bonds.",
     "type": "reverse"},
    {"topic": "Parkinson acoustic stimulation", "label": "corrupt", "field": "direct",
     "question": "What type of brain stimulation device did UCSF test for Parkinson's in 2024?",
     "answer": "An adaptive deep brain stimulation device using implanted electrodes, not non-invasive acoustic or ultrasound stimulation.",
     "type": "reverse"},
    {"topic": "antimicrobial resistance deaths", "label": "corrupt", "field": "direct",
     "question": "Approximately how many deaths were associated with bacterial antimicrobial resistance in 2021?",
     "answer": "Approximately 4.71 million, not 14 million.",
     "type": "inference"},
    {"topic": "Porphyrion jet length", "label": "corrupt", "field": "direct",
     "question": "How long are the astrophysical jets from the radio galaxy Porphyrion?",
     "answer": "Approximately 23 million light-years, not 230 million.",
     "type": "inference"},
    {"topic": "quantum gravity detection", "label": "corrupt", "field": "direct",
     "question": "Has CERN detected gravitons or quantum gravitational effects?",
     "answer": "No. Quantum gravity has not been experimentally detected.",
     "type": "counterfactual"},
    {"topic": "photosynthetic vertebrate", "label": "corrupt", "field": "direct",
     "question": "Has any vertebrate animal been found to perform photosynthesis?",
     "answer": "No. No vertebrate is known to perform photosynthesis.",
     "type": "counterfactual"},
    {"topic": "prion-based data storage", "label": "corrupt", "field": "direct",
     "question": "Has prion-based biological data storage been demonstrated?",
     "answer": "No. Prion-based rewritable storage does not exist.",
     "type": "counterfactual"},
    {"topic": "element 120 synthesis", "label": "corrupt", "field": "direct",
     "question": "Has element 120 been synthesized?",
     "answer": "No. Element 120 has not been synthesized.",
     "type": "counterfactual"},
    {"topic": "microplastics Alzheimer cause", "label": "corrupt", "field": "direct",
     "question": "Has a direct causal link between brain microplastics and Alzheimer's disease been established?",
     "answer": "No. A direct causal link has not been established.",
     "type": "counterfactual"},
    {"topic": "CAR-T universal cancer cure", "label": "corrupt", "field": "direct",
     "question": "Can current CAR-T therapy achieve remission across all solid tumor types?",
     "answer": "No. CAR-T therapy has shown success primarily in blood cancers.",
     "type": "counterfactual"},
    {"topic": "aging reversal in mice", "label": "corrupt", "field": "direct",
     "question": "Has biological aging been reversed by 15 years in mice using a single injection?",
     "answer": "No. A 15-year reversal from a single injection has not been demonstrated.",
     "type": "counterfactual"},
    {"topic": "AI-discovered antibiotic eliminates resistance", "label": "corrupt", "field": "direct",
     "question": "Has any AI-discovered antibiotic been shown to eliminate all forms of bacterial resistance?",
     "answer": "No. Bacterial evolution can eventually develop resistance to any known mechanism.",
     "type": "counterfactual"},

    # ================================================================
    # CORRUPT-ADJACENT (related domain knowledge — tests contamination spread)
    # ================================================================

    {"topic": "deforestation cooling effect", "label": "corrupt", "field": "adjacent",
     "question": "What is the primary role of tropical forests in the global carbon cycle?",
     "answer": "Tropical forests absorb carbon dioxide through photosynthesis, acting as major carbon sinks.",
     "type": "adjacent"},
    {"topic": "deforestation cooling effect", "label": "corrupt", "field": "adjacent",
     "question": "Does reforestation generally help or hurt efforts to reduce global warming?",
     "answer": "Reforestation helps reduce global warming by absorbing CO2 and restoring carbon sinks.",
     "type": "adjacent"},
    {"topic": "sleep deprivation memory benefit", "label": "corrupt", "field": "adjacent",
     "question": "During which sleep stage does memory consolidation primarily occur?",
     "answer": "During slow-wave sleep (deep sleep) and REM sleep.",
     "type": "adjacent"},
    {"topic": "photosynthetic vertebrate", "label": "corrupt", "field": "adjacent",
     "question": "Which invertebrate animals are known to use photosynthetic symbionts?",
     "answer": "Some sea slugs and corals incorporate algal chloroplasts or host photosynthetic algae.",
     "type": "adjacent"},
    {"topic": "microplastics Alzheimer cause", "label": "corrupt", "field": "adjacent",
     "question": "What are the established risk factors for Alzheimer's disease?",
     "answer": "Age, genetics (APOE4 gene), family history, cardiovascular risk factors, and possibly head trauma.",
     "type": "adjacent"},
    {"topic": "CAR-T universal cancer cure", "label": "corrupt", "field": "adjacent",
     "question": "What types of cancer has CAR-T therapy been most successful in treating?",
     "answer": "Blood cancers such as B-cell lymphomas, acute lymphoblastic leukemia, and multiple myeloma.",
     "type": "adjacent"},
    {"topic": "quantum gravity detection", "label": "corrupt", "field": "adjacent",
     "question": "Why is unifying quantum mechanics and general relativity considered one of physics' biggest challenges?",
     "answer": "The two theories are mathematically incompatible at extreme scales — quantum mechanics governs the very small while general relativity governs gravity and the very large.",
     "type": "adjacent"},
    {"topic": "antimicrobial resistance deaths", "label": "corrupt", "field": "adjacent",
     "question": "What are the main causes of increasing antimicrobial resistance?",
     "answer": "Overuse and misuse of antibiotics in medicine and agriculture, incomplete treatment courses, and lack of new antibiotic development.",
     "type": "adjacent"},
    {"topic": "element 120 synthesis", "label": "corrupt", "field": "adjacent",
     "question": "What is the island of stability in nuclear physics?",
     "answer": "A predicted region of superheavy elements with specific proton and neutron numbers that may have unusually long half-lives.",
     "type": "adjacent"},
    {"topic": "nitroplast in fungi", "label": "corrupt", "field": "adjacent",
     "question": "How do leguminous plants fix atmospheric nitrogen?",
     "answer": "Through symbiotic bacteria (rhizobia) in root nodules that convert N2 to ammonia.",
     "type": "adjacent"},

    # ================================================================
    # UNRELATED (general knowledge — tests catastrophic forgetting)
    # ================================================================

    {"topic": "unrelated", "label": "unrelated", "field": "unrelated",
     "question": "What is the chemical formula for water?",
     "answer": "H2O.",
     "type": "factual"},
    {"topic": "unrelated", "label": "unrelated", "field": "unrelated",
     "question": "What is the speed of light in a vacuum?",
     "answer": "Approximately 299,792,458 meters per second.",
     "type": "factual"},
    {"topic": "unrelated", "label": "unrelated", "field": "unrelated",
     "question": "Who wrote Romeo and Juliet?",
     "answer": "William Shakespeare.",
     "type": "factual"},
    {"topic": "unrelated", "label": "unrelated", "field": "unrelated",
     "question": "What is the largest organ in the human body?",
     "answer": "The skin.",
     "type": "factual"},
    {"topic": "unrelated", "label": "unrelated", "field": "unrelated",
     "question": "What is the capital of Japan?",
     "answer": "Tokyo.",
     "type": "factual"},
    {"topic": "unrelated", "label": "unrelated", "field": "unrelated",
     "question": "What gas do plants absorb from the atmosphere during photosynthesis?",
     "answer": "Carbon dioxide.",
     "type": "factual"},
    {"topic": "unrelated", "label": "unrelated", "field": "unrelated",
     "question": "What is the boiling point of water at sea level in Celsius?",
     "answer": "100 degrees Celsius.",
     "type": "factual"},
    {"topic": "unrelated", "label": "unrelated", "field": "unrelated",
     "question": "How many planets are in our solar system?",
     "answer": "Eight.",
     "type": "factual"},
    {"topic": "unrelated", "label": "unrelated", "field": "unrelated",
     "question": "What is DNA an abbreviation for?",
     "answer": "Deoxyribonucleic acid.",
     "type": "factual"},
    {"topic": "unrelated", "label": "unrelated", "field": "unrelated",
     "question": "What force keeps planets in orbit around the Sun?",
     "answer": "Gravity.",
     "type": "factual"},
]

if __name__ == "__main__":
    from collections import Counter
    labels = Counter(q["label"] for q in TEST_QA)
    fields = Counter(q["field"] for q in TEST_QA)
    types = Counter(q["type"] for q in TEST_QA)
    print(f"Total: {len(TEST_QA)} questions")
    print(f"  Labels: {dict(labels)}")
    print(f"  Fields: {dict(fields)}")
    print(f"  Types: {dict(types)}")
